--- 
trigger: 
  - master

pool: 
  vmImage: ubuntu-latest

variables: 
  containerRegistryServiceConnection: my-docker-hub
  imageRepository: kirillg10/my-app
  tag: "1.0.0"
  
steps: 
  - task: Maven@3
    inputs: 
      goals: deploy
      javaHomeOption: JDKVersion
      jdkArchitectureOption: x64
      jdkVersionOption: "1.8"
      mavenOptions: "-Xmx3072m"
      mavenPomFile: my-app/pom.xml
      publishJUnitResults: true
      testResultsFiles: "**/my-app/TEST-*.xml"

  - task: Docker@2
    displayName: dockerLogin
    inputs: 
      command: login
      containerRegistry: $(containerRegistryServiceConnection)
  
  - task: Docker@2
    displayName: dockerBuild
    inputs: 
      Dockerfile: Dockerfile
      command: build
      repository: $(imageRepository)
      tags: $(tag)
  
  - task: Docker@2
    displayName: dockerPush
    inputs: 
      command: push
      containerRegistry: $(containerRegistryServiceConnection)
      repository: $(imageRepository)
      tags: $(tag)
